/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pwr_jk_jni_NativeConvolution */

#ifndef _Included_pl_pwr_jk_jni_NativeConvolution
#define _Included_pl_pwr_jk_jni_NativeConvolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pwr_jk_jni_NativeConvolution
 * Method:    nativelyCalculateConvolution
 * Signature: ([[Ljava/lang/Double;[[Ljava/lang/Double;)[[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_pl_pwr_jk_jni_NativeConvolution_nativelyCalculateConvolution
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
